remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-seo-tag

title: Kraken Hunter
description: Learn how to use Sysdig Secure

logo: /assets/logo/sysdig.png

color_scheme: kraken

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

back_to_top: true
back_to_top_text: "Back to top"
